FROM maven:ibmjava-alpine AS build

WORKDIR /app

COPY src src

COPY pom.xml pom.xml

RUN mvn clean package

#
# Package Stage
#

FROM openjdk:8-alpine

WORKDIR /app

COPY --from=build /app/target/websocket-demo-0.0.1-SNAPSHOT.jar app.jar

CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "app.jar"]






